package:
  name: pythonocc-core
  version: 0.16.3dev

source:
    git_url: https://github.com/tpaviot/pythonocc-core.git             [unix]
    git_tag: master # only master contains important fixes             [unix]
    fn: pythonocc-core-master.zip                                      [win]
    url: https://github.com/tpaviot/pythonocc-core/archive/master.zip  [win]
    patches:
      - fix_graphicshr_location.patch

build:
  number: 2
  binary_relocation: true
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - ninja             [win]
    - patch             [win]
    - cmake
    - python
    - opencascade_community_edition ==0.16.1
    - swig
    - gcc               [linux]

  run:
    - python
    - opencascade_community_edition ==0.16.1

test:
  imports:
    - OCC
    - OCC.BRepPrimAPI


about:
  home: https://github.com/tpaviot/pythonocc-core
  summary: https://github.com/tpaviot/pythonocc-core/blob/master/README.md
  license: LGPL

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
